const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const querystring = require('querystring');

const ENV_FILE = path.join(__dirname, '.env');
if (fs.existsSync(ENV_FILE)) {
  fs.readFileSync(ENV_FILE, 'utf8').split(/\r?\n/).forEach(line => {
    const m = line.match(/^([^#=]+)=(.*)$/);
    if (m && !process.env[m[1].trim()]) process.env[m[1].trim()] = m[2].trim();
  });
}

const PORT = process.env.PORT || 3000;
const BASE_URL = (process.env.BASE_URL || `http://localhost:${PORT}`).replace(/\/$/, '');
const PAYFAST_MODE = process.env.PAYFAST_MODE || 'sandbox';
const PAYFAST_URL = PAYFAST_MODE === 'live' ? 'https://www.payfast.co.za/eng/process' : 'https://sandbox.payfast.co.za/eng/process';
const MERCHANT_ID = process.env.PAYFAST_MERCHANT_ID || '10000100';
const MERCHANT_KEY = process.env.PAYFAST_MERCHANT_KEY || '46f0cd694581a';
const PASSPHRASE = process.env.PAYFAST_PASSPHRASE || '';
const ADMIN_TOKEN = process.env.ADMIN_TOKEN || 'change-this-long-secret';
const PRICE = process.env.PRODUCT_PRICE || '199.00';
const DATA_DIR = path.join(__dirname, 'data');
const PUBLIC_DIR = path.join(__dirname, 'public');
const DOWNLOAD_DIR = path.join(PUBLIC_DIR, 'downloads');
const ORDERS_FILE = path.join(DATA_DIR, 'orders.json');
const VENDORS_FILE = path.join(DATA_DIR, 'vendors.json');
const PRODUCT_FILE = 'faith-personified-my-journey.pdf';
fs.mkdirSync(DATA_DIR, { recursive: true });
fs.mkdirSync(DOWNLOAD_DIR, { recursive: true });
for (const f of [ORDERS_FILE, VENDORS_FILE]) if (!fs.existsSync(f)) fs.writeFileSync(f, '[]');

function readJson(file){ try { return JSON.parse(fs.readFileSync(file,'utf8') || '[]'); } catch { return []; } }
function writeJson(file,data){ fs.writeFileSync(file, JSON.stringify(data,null,2)); }
function esc(s=''){ return String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function body(req){ return new Promise(resolve => { let d=''; req.on('data', c => d += c); req.on('end', () => resolve(querystring.parse(d))); }); }
function send(res, status, html, type='text/html'){ res.writeHead(status, {'Content-Type': type, 'Cache-Control': 'no-store'}); res.end(html); }
function page(title, content){ return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | LegacyMart</title><link rel="stylesheet" href="/styles.css"></head><body><header><a class="brand" href="/"><span class="mark">LM</span><span><b>LegacyMart</b><small>Trade • Community • Lasting Impact</small></span></a><nav><a href="/shop">Shop</a><a href="/faith-personified">Faith Personified</a><a href="/become-a-vendor">Become a Vendor</a><a href="/how-it-works">How It Works</a><a href="/about">About</a></nav></header><main>${content}</main><footer><b>LegacyMart</b><p>Buy with purpose. Sell with purpose. Build legacy.</p><p><a href="/privacy">Privacy</a> · <a href="/refunds">Refunds</a> · <a href="/terms">Terms</a> · <a href="/vendor-terms">Vendor Terms</a> · <a href="/admin">Admin</a></p></footer></body></html>`; }
function sign(data){ const clean = {...data}; delete clean.signature; let out = Object.keys(clean).filter(k => clean[k] !== '').sort().map(k => `${k}=${encodeURIComponent(clean[k]).replace(/%20/g,'+')}`).join('&'); if (PASSPHRASE) out += `&passphrase=${encodeURIComponent(PASSPHRASE).replace(/%20/g,'+')}`; return crypto.createHash('md5').update(out).digest('hex'); }

function home(){ return page('Home', `<section class="hero"><div><p class="eyebrow">A purpose-driven marketplace</p><h1>Buy. Sell. Build. Grow.</h1><p class="lead">LegacyMart helps authors, creators, educators, ministries, small businesses and entrepreneurs sell products online with dignity, trust and lasting impact.</p><p><a class="btn primary" href="/faith-personified">Buy the Ebook</a><a class="btn ghost" href="/become-a-vendor">Become a Vendor</a></p></div><div class="hero-card"><div class="bigmark">LM</div><h2>Trade • Community • Lasting Impact</h2><p>Launching first with Bevan Shelton’s ebook, then opening to selected vendors.</p></div></section><section class="grid"><article><h2>Faith Personified – My Journey</h2><p>A true-life journey of faith, survival, leadership, ministry, family, entrepreneurship, healing, purpose and divine restoration.</p><p class="price">R${PRICE}</p><a class="btn primary" href="/checkout">Buy via PayFast</a></article><article class="dark"><h2>Start selling on LegacyMart</h2><p>Apply if you have ebooks, printed books, clothing, courses, digital downloads, faith-based resources, study guides, business tools or creative products.</p><a class="btn light" href="/become-a-vendor">Apply to Sell</a></article></section>`); }
function shop(){ return page('Shop', `<section><h1>LegacyMart Shop</h1><div class="product"><h2>Faith Personified – My Journey</h2><p>By Bevan Shelton</p><p>Downloadable ebook. Secure PayFast checkout. Instant access after successful payment confirmation.</p><p class="price">R${PRICE}</p><a class="btn primary" href="/checkout">Buy Ebook</a></div></section>`); }
function faith(){ return page('Faith Personified', `<section><p class="eyebrow">Featured launch product</p><h1>Faith Personified – My Journey</h1><h2>By Bevan Shelton</h2><p class="lead">This book is a true-life journey of faith, survival, rejection, leadership, ministry, family, entrepreneurship, healing, purpose and divine restoration.</p><p>It speaks to the wounded, the dreamer, the believer, the leader, the entrepreneur and the person who knows there is still more inside them.</p><p><b>Format:</b> PDF ebook. <b>Delivery:</b> Instant download after PayFast confirms payment.</p><p class="price">R${PRICE}</p><a class="btn primary" href="/checkout">Buy Now via PayFast</a></section>`); }
function checkout(){ return page('Checkout', `<section><h1>Secure Checkout</h1><div class="checkout"><div><h2>Faith Personified – My Journey</h2><p>Digital ebook PDF delivered after successful PayFast payment confirmation.</p><p class="price">R${PRICE}</p></div><form method="post" action="/payfast/start" class="form"><input name="name_first" placeholder="First name" required><input name="name_last" placeholder="Last name" required><input name="email_address" type="email" placeholder="Email address" required><button class="btn primary" type="submit">Continue to PayFast</button><p class="small">Downloads are protected until payment is confirmed.</p></form></div></section>`); }
function vendor(){ return page('Become a Vendor', `<section><h1>Start Selling on LegacyMart</h1><p class="lead">Turn your book, product, course, message or creative gift into an income-generating online store.</p><form method="post" action="/vendor/apply" class="form"><input name="full_name" placeholder="Full name" required><input name="business_name" placeholder="Business name" required><input name="email" type="email" placeholder="Email" required><input name="whatsapp" placeholder="WhatsApp number" required><input name="province" placeholder="Province"><select name="category"><option>Ebooks</option><option>Printed books</option><option>Clothing</option><option>Courses</option><option>Faith-based resources</option><option>Creative products</option><option>Business templates</option></select><textarea name="description" placeholder="Tell us what you want to sell" required></textarea><label><input type="checkbox" required> I agree to the vendor terms.</label><button class="btn primary" type="submit">Submit Vendor Application</button></form></section>`); }
function simple(title, text){ return page(title, `<section><h1>${esc(title)}</h1><p class="lead">${text}</p></section>`); }
function admin(query){ if (query.token !== ADMIN_TOKEN) return page('Admin', `<section><h1>Admin</h1><p>Use:</p><code>/admin?token=YOUR_ADMIN_TOKEN</code></section>`); const orders = readJson(ORDERS_FILE); const vendors = readJson(VENDORS_FILE); const rows = orders.map(o => `<tr><td>${esc(o.id)}</td><td>${esc(o.email)}</td><td>${esc(o.status)}</td><td>R${esc(o.amount)}</td><td>${esc(o.created_at)}</td></tr>`).join(''); const vrows = vendors.map(v => `<tr><td>${esc(v.full_name)}</td><td>${esc(v.business_name)}</td><td>${esc(v.email)}</td><td>${esc(v.category)}</td><td>${esc(v.created_at)}</td></tr>`).join(''); return page('Admin', `<section><h1>Admin Dashboard</h1><p><a class="btn ghost" href="/admin/orders.csv?token=${ADMIN_TOKEN}">Export Orders CSV</a><a class="btn ghost" href="/admin/vendors.csv?token=${ADMIN_TOKEN}">Export Vendors CSV</a></p><h2>Orders</h2><table><tr><th>Order</th><th>Email</th><th>Status</th><th>Amount</th><th>Created</th></tr>${rows || '<tr><td colspan="5">No orders yet.</td></tr>'}</table><h2>Vendor Applications</h2><table><tr><th>Name</th><th>Business</th><th>Email</th><th>Category</th><th>Created</th></tr>${vrows || '<tr><td colspan="5">No vendor applications yet.</td></tr>'}</table></section>`); }
function csv(rows, fields){ return [fields.join(','), ...rows.map(r => fields.map(f => `"${String(r[f] || '').replace(/"/g,'""')}"`).join(','))].join('\n'); }
function staticFile(req,res){ const safe = path.normalize(decodeURIComponent(req.url.split('?')[0])).replace(/^\/+/, ''); const file = path.join(PUBLIC_DIR, safe); if (!file.startsWith(PUBLIC_DIR) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return false; const ext = path.extname(file).toLowerCase(); const types = {'.css':'text/css','.pdf':'application/pdf'}; res.writeHead(200, {'Content-Type': types[ext] || 'application/octet-stream'}); fs.createReadStream(file).pipe(res); return true; }

http.createServer(async (req,res) => {
  const url = new URL(req.url, BASE_URL);
  if (req.method === 'GET' && staticFile(req,res)) return;
  if (req.method === 'GET' && url.pathname === '/') return send(res,200,home());
  if (req.method === 'GET' && url.pathname === '/shop') return send(res,200,shop());
  if (req.method === 'GET' && url.pathname === '/faith-personified') return send(res,200,faith());
  if (req.method === 'GET' && url.pathname === '/checkout') return send(res,200,checkout());
  if (req.method === 'GET' && url.pathname === '/become-a-vendor') return send(res,200,vendor());
  if (req.method === 'GET' && url.pathname === '/how-it-works') return send(res,200,simple('How It Works','Buyers browse, buy, pay securely through PayFast and receive downloads or delivery. Vendors apply, get approved, upload products, fulfil orders and grow income.'));
  if (req.method === 'GET' && url.pathname === '/about') return send(res,200,simple('About LegacyMart','LegacyMart is a South African-born, purpose-driven marketplace for trade, community and lasting impact.'));
  if (req.method === 'GET' && url.pathname === '/privacy') return send(res,200,simple('Privacy Policy','We collect buyer and vendor information only to process orders, vendor applications, communication and platform operations, following POPIA principles.'));
  if (req.method === 'GET' && url.pathname === '/refunds') return send(res,200,simple('Refund Policy','Digital products are generally non-refundable once downloaded, unless defective or incorrectly supplied. Physical product returns depend on seller terms and consumer law.'));
  if (req.method === 'GET' && url.pathname === '/terms') return send(res,200,simple('Terms and Conditions','Users must provide accurate information, use PayFast checkout lawfully, respect intellectual property and follow marketplace rules.'));
  if (req.method === 'GET' && url.pathname === '/vendor-terms') return send(res,200,simple('Vendor Terms','Vendors are responsible for product accuracy, legality, quality, fulfilment, customer support and compliance with platform standards.'));
  if (req.method === 'GET' && url.pathname === '/contact') return send(res,200,simple('Contact','For sales, support and vendor enquiries, use the LegacyMart contact channels published at launch.'));
  if (req.method === 'GET' && url.pathname === '/health') return send(res,200,JSON.stringify({ok:true,service:'LegacyMart'}),'application/json');
  if (req.method === 'GET' && url.pathname === '/admin') return send(res,200,admin(Object.fromEntries(url.searchParams.entries())));
  if (req.method === 'GET' && url.pathname === '/admin/orders.csv') { if (url.searchParams.get('token') !== ADMIN_TOKEN) return send(res,403,'Forbidden','text/plain'); return send(res,200,csv(readJson(ORDERS_FILE),['id','email','status','amount','created_at']),'text/csv'); }
  if (req.method === 'GET' && url.pathname === '/admin/vendors.csv') { if (url.searchParams.get('token') !== ADMIN_TOKEN) return send(res,403,'Forbidden','text/plain'); return send(res,200,csv(readJson(VENDORS_FILE),['full_name','business_name','email','whatsapp','province','category','description','created_at']),'text/csv'); }
  if (req.method === 'POST' && url.pathname === '/vendor/apply') { const b = await body(req); const vendors = readJson(VENDORS_FILE); vendors.push({...b, created_at:new Date().toISOString()}); writeJson(VENDORS_FILE, vendors); return send(res,200,page('Vendor Application Received','<section><h1>Application Received</h1><p>Thank you. LegacyMart will review your application before approval.</p><a class="btn primary" href="/">Back Home</a></section>')); }
  if (req.method === 'POST' && url.pathname === '/payfast/start') { const b = await body(req); const id = 'LM-' + Date.now(); const orders = readJson(ORDERS_FILE); orders.push({id,email:b.email_address,status:'pending',amount:PRICE,created_at:new Date().toISOString()}); writeJson(ORDERS_FILE, orders); const data = {merchant_id:MERCHANT_ID, merchant_key:MERCHANT_KEY, return_url:`${BASE_URL}/thank-you?order=${id}`, cancel_url:`${BASE_URL}/checkout?cancelled=1`, notify_url:`${BASE_URL}/payfast/itn`, name_first:b.name_first || '', name_last:b.name_last || '', email_address:b.email_address || '', m_payment_id:id, amount:PRICE, item_name:'Faith Personified - My Journey Ebook'}; data.signature = sign(data); const inputs = Object.entries(data).map(([k,v]) => `<input type="hidden" name="${esc(k)}" value="${esc(v)}">`).join(''); return send(res,200,page('Redirecting to PayFast', `<section><h1>Redirecting to PayFast</h1><form id="pf" method="post" action="${PAYFAST_URL}">${inputs}<button class="btn primary" type="submit">Pay Now</button></form><script>document.getElementById('pf').submit()</script></section>`)); }
  if (req.method === 'POST' && url.pathname === '/payfast/itn') { const b = await body(req); const orders = readJson(ORDERS_FILE); const order = orders.find(o => o.id === b.m_payment_id); if (order) { order.status = b.payment_status === 'COMPLETE' ? 'paid' : String(b.payment_status || 'pending').toLowerCase(); order.itn = b; order.updated_at = new Date().toISOString(); writeJson(ORDERS_FILE, orders); } return send(res,200,'OK','text/plain'); }
  if (req.method === 'GET' && url.pathname === '/thank-you') { const id = url.searchParams.get('order'); return send(res,200,page('Thank You', `<section><h1>Thank you</h1><p>Your order reference is <b>${esc(id || '')}</b>.</p><p>When PayFast confirms payment, your download will unlock.</p><a class="btn primary" href="/download?order=${esc(id || '')}">Check Download</a></section>`)); }
  if (req.method === 'GET' && url.pathname === '/download') { const id = url.searchParams.get('order'); const order = readJson(ORDERS_FILE).find(o => o.id === id); if (!order || order.status !== 'paid') return send(res,403,page('Download Locked','<section><h1>Download locked</h1><p>Your download unlocks after successful payment confirmation.</p></section>')); const file = path.join(DOWNLOAD_DIR, PRODUCT_FILE); if (!fs.existsSync(file)) return send(res,404,page('Ebook Not Uploaded','<section><h1>Ebook file not uploaded yet</h1><p>Upload the final PDF into public/downloads/faith-personified-my-journey.pdf.</p></section>')); res.writeHead(200, {'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${PRODUCT_FILE}"`}); return fs.createReadStream(file).pipe(res); }
  return send(res,404,page('Not Found','<section><h1>Page not found</h1><a class="btn primary" href="/">Back Home</a></section>'));
}).listen(PORT, () => console.log(`LegacyMart running on ${BASE_URL}`));
